import { fetchEvent, fetchMatrix, fetchBlindspots } from '@/lib/api';
import PerspectiveMatrix from '@/components/PerspectiveMatrix';
import OrientationBar, { getBias } from '@/components/OrientationBar';
import Link from 'next/link';
import { Inter } from 'next/font/google';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'], weight: ['400', '500', '600', '700', '800'] });

const t = {
  en: {
    home: "Home",
    blindspot: "Blindspot",
    sources: "Sources",
    back: "← Back to Events",
    summary: "Event Summary",
    loadingSummary: "Summary is still being generated by the NLP engine...",
    analysis: "Perspective Analysis",
    timeline: "Timeline",
    coverage: "Coverage Breakdown",
    articles: "Total Articles:",
    sources: "Total Sources:",
    blindspots: "Blindspots Detected",
    noBlindspots: "No significant blindspots detected across orientations.",
    level: "Level"
  },
  ta: {
    home: "முகப்பு",
    blindspot: "தவறவிடப்பட்ட செய்தி",
    sources: "ஆதாரங்கள்",
    back: "← நிகழ்வுகளுக்குத் திரும்புக",
    summary: "நிகழ்வுச் சுருக்கம்",
    loadingSummary: "சுருக்கம் உருவாக்கப்படுகிறது...",
    analysis: "கண்ணோட்டப் பகுப்பாய்வு",
    timeline: "காலவரிசை",
    coverage: "செய்தி வெளியீட்டு விவரம்",
    articles: "மொத்தக் கட்டுரைகள்:",
    sources: "மொத்த ஆதாரங்கள்:",
    blindspots: "கண்டறியப்பட்ட தவறவிடப்பட்ட செய்திகள்",
    noBlindspots: "குறிப்பிடத்தக்க தவறவிடப்பட்ட செய்திகள் எதுவும் கண்டறியப்படவில்லை.",
    level: "தீவிர நிலை"
  }
};

export default async function EventPage(props) {
  const { id } = await props.params;
  const searchParams = await props.searchParams;
  const lang = searchParams?.lang === 'ta' ? 'ta' : 'en';
  const strings = t[lang];

  let event = null;
  let matrix = {};
  let blindspots = [];

  try {
    event = await fetchEvent(id, lang);
    matrix = await fetchMatrix(id, lang);
    const bsResponse = await fetchBlindspots(id, lang);
    blindspots = bsResponse.blindspots || [];
  } catch (err) {
    console.error(err);
    return <div style={{ color: 'var(--color-negative)', padding: '2rem' }}>Failed to load event details.</div>;
  }

  return (
    <div className={inter.className} style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column', backgroundColor: '#f7f5ef', color: '#171717', fontFamily: 'Inter, sans-serif', fontWeight: 600 }}>
      <style>{`
        @media (max-width: 800px) {
          .event-layout {
            grid-template-columns: 1fr !important;
          }
        }

        @media (max-width: 620px) {
          .event-main {
            padding: 24px 18px 48px !important;
          }

          .event-title {
            font-size: 2rem !important;
          }

          .event-nav {
            flex-wrap: wrap;
          }
        }
      `}</style>

      <Header lang={lang} activePage="home" />

      <main className="event-main" style={{ maxWidth: '1200px', margin: '0 auto', padding: '32px', width: '100%', boxSizing: 'border-box' }}>
        <header
          style={{
            marginBottom: '32px',
            paddingBottom: '24px',
            borderBottom: '1px solid #171717',
          }}
        >
          <Link
            href={`/?lang=${lang}`}
            style={{
              color: '#555',
              fontWeight: 600,
              fontSize: '0.78rem',
              marginBottom: '18px',
              display: 'inline-block',
              textDecoration: 'none',
            }}
          >
            {strings.back}
          </Link>

          <h1
            className="event-title"
            style={{
              fontSize: '2.5rem',
              fontWeight: 600,
              lineHeight: 1.15,
              margin: 0,
              color: '#111',
              letterSpacing: '-0.04em',
            }}
          >
            {event.title}
          </h1>

          <div style={{ marginTop: '20px', maxWidth: '900px' }}>
            <div
              style={{
                fontSize: '0.72rem',
                textTransform: 'uppercase',
                letterSpacing: '0.08em',
                fontWeight: 600,
                color: '#777',
                marginBottom: '8px',
              }}
            >
              {strings.summary}
            </div>

            {event.summary ? (
              <p style={{
                margin: 0,
                color: '#444',
                lineHeight: 1.65,
                fontSize: '1rem',
                wordBreak: 'break-word',
              }}>
                {event.summary.replace(/<[^>]*>?/gm, '')}
              </p>
            ) : (
              <p style={{ margin: 0, color: '#777', lineHeight: 1.65, fontSize: '1rem' }}>
                {strings.loadingSummary}
              </p>
            )}
          </div>
        </header>

        <div className="event-layout" style={{ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) 320px', gap: '40px' }}>
          {/* Left Column: Timeline & Perspectives */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '32px' }}>
            <section>
              <h2 style={{ fontSize: '1.4rem', fontWeight: 700, marginBottom: '16px', color: '#111' }}>{strings.analysis}</h2>
              <PerspectiveMatrix matrix={matrix} />
            </section>

            <section>
              <h2 style={{ fontSize: '1.4rem', fontWeight: 700, marginBottom: '16px', color: '#111' }}>{strings.timeline}</h2>
              <div style={{ padding: '24px', backgroundColor: 'transparent', borderTop: '1px solid #bdb9b0', borderBottom: '1px solid #bdb9b0' }}>
                {event.articles?.map((article, idx) => {
                  const bias = getBias(article.orientation);
                  return (
                    <div key={article.id} style={{
                      display: 'flex',
                      gap: '16px',
                      marginBottom: idx < event.articles.length - 1 ? '24px' : '0',
                      paddingBottom: idx < event.articles.length - 1 ? '24px' : '0',
                      borderBottom: idx < event.articles.length - 1 ? '1px solid #d1cec6' : 'none'
                    }}>
                      <div style={{
                        width: '12px',
                        height: '12px',
                        borderRadius: '50%',
                        background: bias.color,
                        marginTop: '6px',
                        border: bias.border ? `1px solid ${bias.border}` : 'none'
                      }} />
                      <div>
                        <a href={article.url} target="_blank" rel="noreferrer" style={{ fontFamily: 'var(--font-inter), sans-serif', fontWeight: 600, fontSize: '1rem', color: '#111', textDecoration: 'none' }}>
                          {article.title}
                        </a>
                        <div style={{ display: 'flex', gap: '12px', marginTop: '8px', fontSize: '0.85rem', color: '#6b7280', alignItems: 'center' }}>
                          <span style={{
                            backgroundColor: bias.color,
                            color: bias.textColor,
                            border: bias.border ? `1px solid ${bias.border}` : 'none',
                            padding: '2px 6px',
                            borderRadius: '4px',
                            fontSize: '0.7rem',
                            fontWeight: 'bold',
                            textTransform: 'uppercase'
                          }}>
                            {bias.label}
                          </span>
                          <span style={{ fontWeight: 'normal' }}>{article.source_id}</span>
                          <span style={{ fontWeight: 'normal' }}>•</span>
                          <span style={{ fontWeight: 'normal' }}>{new Date(article.published_at).toLocaleString()}</span>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            </section>
          </div>

          {/* Right Column: Context & Metadata */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
            <div style={{ padding: '24px', backgroundColor: 'transparent', borderTop: '1px solid #bdb9b0', borderBottom: '1px solid #bdb9b0' }}>
              <h3 style={{ fontSize: '1.2rem', fontWeight: 700, marginBottom: '16px', color: '#111' }}>{strings.coverage}</h3>
              <OrientationBar coverage={event.coverage} />
              <div style={{ marginTop: '24px', display: 'flex', justifyContent: 'space-between', color: '#4b5563' }}>
                <span>{strings.articles}</span>
                <span style={{ fontWeight: 600, color: '#111' }}>{event.article_count}</span>
              </div>
              <div style={{ marginTop: '8px', display: 'flex', justifyContent: 'space-between', color: '#4b5563' }}>
                <span>{strings.sources}</span>
                <span style={{ fontWeight: 600, color: '#111' }}>{event.source_count}</span>
              </div>
            </div>

            <div style={{ padding: '24px', backgroundColor: 'transparent', borderTop: '1px solid #bdb9b0', borderBottom: '1px solid #bdb9b0' }}>
              <h3 style={{ fontSize: '1.2rem', fontWeight: 700, marginBottom: '16px', color: '#dc2626' }}>{strings.blindspots}</h3>
              {blindspots.length > 0 ? (
                <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: '12px' }}>
                  {blindspots.map((bs, i) => {
                    const reason = bs.evidence?.reason || bs.type || 'Undetected gap';
                    return (
                      <li key={i} style={{ padding: '12px', background: 'transparent', borderLeft: '3px solid #dc2626' }}>
                        <div style={{ fontSize: '0.8rem', color: '#dc2626', textTransform: 'uppercase', marginBottom: '4px', fontWeight: 'bold' }}>{strings.level} {bs.score?.toFixed(1) || 'High'}</div>
                        <p style={{ fontSize: '0.9rem', color: '#111' }}>{reason}</p>
                      </li>
                    );
                  })}
                </ul>
              ) : (
                <p style={{ color: '#6b7280', fontSize: '0.95rem' }}>{strings.noBlindspots}</p>
              )}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
